# Generated by Django 4.2.2 on 2023-06-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helporder",
            name="create_datetime",
            field=models.DateTimeField(null=True, verbose_name="创建时间"),
        ),
        migrations.AddField(
            model_name="helporder",
            name="update_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
        ),
    ]
