# Generated by Django 4.2.2 on 2023-06-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_helporder_update_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="alarm",
            field=models.SmallIntegerField(
                choices=[(0, "无预警"), (1, "预警！")], default=0, verbose_name="预警状态"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rest_time",
            field=models.SmallIntegerField(default=7, verbose_name="剩余天数"),
        ),
    ]
