# Generated by Django 4.2.2 on 2023-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_order_alarm_order_rest_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="alarm",
            field=models.SmallIntegerField(
                choices=[(0, "无预警"), (1, "预警！"), (2, "超时！")],
                default=0,
                verbose_name="预警状态",
            ),
        ),
    ]
