# Generated by Django 4.2.2 on 2023-06-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_alter_order_alarm"),
    ]

    operations = [
        migrations.CreateModel(
            name="kpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workdeal", models.SmallIntegerField(default=0, verbose_name="完成工单数")),
                ("helpdeal", models.SmallIntegerField(default=0, verbose_name="完成协助数")),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops",
                        to="app01.userinfo",
                        verbose_name="操作员",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="depart_kpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workdeal",
                    models.SmallIntegerField(default=0, verbose_name="部门完成工单数"),
                ),
                (
                    "delaydeal",
                    models.SmallIntegerField(default=0, verbose_name="部门超时工单数"),
                ),
                (
                    "dpart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.department",
                        verbose_name="处理部门",
                    ),
                ),
            ],
        ),
    ]
